# **NumPy**
https://www.w3schools.com/python/numpy/default.asp

In [2]:
#install numpy
#!pip install numpy

In [5]:
#import numpy under the alias np
import numpy as np

In [6]:
#check version
print(np.__version__)

1.26.4


# **Creating a numpy array**

In [8]:
#create a numpy array using the array() function
arr = np.array([10,8,14,20])

#print the array arr
print(arr)

#print the type of arr
print(type(arr))

[10  8 14 20]
<class 'numpy.ndarray'>


In [13]:
# 0-Dimensional array or scalar
arr1 = np.array(12)
print('0-D array: ')
print(arr1)

# 1-D array has 0-D array as its elements
arr2 = np.array([12,10,8,5])
print('1-D array: ')
print(arr2)

# 2-D array has 1-D arrays as its elements
arr3 = np.array([[1,2,3], [4,5,6]])
print('2-D array: ')
print(arr3)

# 3-D array has 2-D arrays as its elements
arr4 = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print('3-D array: ')
print(arr4)

0-D array: 
12
1-D array: 
[12 10  8  5]
2-D array: 
[[1 2 3]
 [4 5 6]]
3-D array: 
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [14]:
# check number of dimensions : ndim
print(arr4.ndim)

3


In [28]:
# shape of an array: number of elements in each dimension
# 2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [15]:
#higher dimensional array : ndmin
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# **Access array elements using array indexing**


In [16]:
# get the first element of an array
arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [17]:
# get the second element of an array
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [18]:
# get the third and fourth element of an array
arr = np.array([1, 2, 3, 4])
print(arr[2]+arr[3])

7


In [19]:
# Access 2-D arrays : use comma separated integers representing the dimension and the index of the element.
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [20]:
# Access 3-D arrays : use comma separated integers representing the dimensions and the index of the element.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [21]:
#negative indexing : Use negative indexing to access an array from the end.
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


# **Numpy array slicing**

taking elements from one given index to another given index. we pass the slice instead of the index: [start:end]
or [start:end:step]

In [22]:
# Slice from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [23]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [25]:
# Slice from beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:5])

[1 2 3 4 5]


In [26]:
# Negative slicing : index 3 from the end to index 1 from the end
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [27]:
# step value to determine the step of the slicin
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]
